# Generated by Django 4.2.7 on 2023-11-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='breed',
            field=models.CharField(choices=[('Namekusei', 'Namekusei'), ('Saiyajin', 'Saiyajin'), ('Human', 'Human')], default='Human', max_length=15),
        ),
    ]
